Copy Files Portfolio to do review
ManarOmari/codeReview pull request #1
Opened 2022-06-06 17:44 UTC by ManarOmari

pull request to review my code by myself

2022-06-06 18:11 UTC, ManarOmari reviewed
- [ No Lintral errors ]

2022-06-07 07:01 UTC, omarsalem7 requested changes
Hi @ManarOmari, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Required Changes ♻️
- [x] You should make a review of the past project and write at least 2 comments in the review.
- [x] You should use GitHub inline comments feature at least once to leave a review comment
- you can refer to [this lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md#how-to-use-github-features) for how to make a good review

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-07 08:30 UTC, ManarOmari reviewed
change require ♻️ 
Please check comments below and make all require changes .

Please,  done all them 
Thanks 😁

2022-06-07 08:30 UTC, ManarOmari commented on index.html
> +            Hello I’m a software developer! I can help you build a product ,
- [ ] to best practice , wrap div to section , <section> tag means that the content inside relates to a single theme ,It is recommended to use the <div> element as a last option and use other various tags such as <main> and <article>.

2022-06-07 08:30 UTC, ManarOmari commented on index.html
> +            <div class="list-icon" id="circle"></div>
- [ ] Notice that you missed  icon -arrow 
🔽 for language and ▶️  for framework and skills

2022-06-07 08:30 UTC, ManarOmari commented on index.html
> +          </div>
- [ ] Please add style for buttons " Active, Hover and Pressed " , to make your project match Figma design .

2022-06-07 08:34 UTC, ManarOmari reviewed
Good Job 👍 
✔️  No lintral error 
✔️  Professional README file

2022-06-07 09:46 UTC, ManarOmari commented
@omarsalem7  please check comment again . 😄

2022-06-07 10:39 UTC, danmainah requested changes
Hi @ManarOmari, 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️  Good use inline comments 
 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-07 10:39 UTC, danmainah commented on index.html
> +            Hello I’m a software developer! I can help you build a product ,
- [x] Kindly make sure your comment is polite and has an explanation of why the changes need to be made.

2022-06-07 10:39 UTC, danmainah commented on index.html
> +          </div>
- [x] Kindly make sure to add an explanation of why the changes need to be made this not only helps the developer understand more but also adds more knowledge.

2022-06-07 10:39 UTC, danmainah commented on index.html
> +            <div class="list-icon" id="circle"></div>
- [x] Kindly refer to the previous comment on the change to implement even here.

2022-06-07 11:31 UTC, ManarOmari commented
@danmainah  please can u check the comments again ?

2022-06-08 07:31 UTC, ManarOmari commented
> Hi @ManarOmari,
> 
> Good job so far! 👏 You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ![you-are-near](https://camo.githubusercontent.com/24e9f6bcfc9c66d6f90ce4fc937ec10b7ba92a648dadb764fb2c37246d36fbce/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f53535231374b36795a5776474359726655682f67697068792e676966) [ ](https://camo.githubusercontent.com/24e9f6bcfc9c66d6f90ce4fc937ec10b7ba92a648dadb764fb2c37246d36fbce/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f53535231374b36795a5776474359726655682f67697068792e676966) ![you-are-near](https://camo.githubusercontent.com/24e9f6bcfc9c66d6f90ce4fc937ec10b7ba92a648dadb764fb2c37246d36fbce/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f53535231374b36795a5776474359726655682f67697068792e676966) [ ](https://camo.githubusercontent.com/24e9f6bcfc9c66d6f90ce4fc937ec10b7ba92a648dadb764fb2c37246d36fbce/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f53535231374b36795a5776474359726655682f67697068792e676966)
> 
> ## Required Changes ♻️
> * [x]  You should make a review of the past project and write at least 2 comments in the review.
> * [x]  You should use GitHub inline comments feature at least once to leave a review comment
> * you can refer to [this lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md#how-to-use-github-features) for how to make a good review
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

please can you review my comments ?

2022-06-08 09:13 UTC, OmarRamoun approved these changes
# 🟢 Project Approved! 🏆

## Hi @ManarOmari 👋

Your project is complete! ✔️ 🏁. This is the First Project 1️⃣ You get Approved ✔️! in microverse 🌐.

Finally, **you did it**! 🎉 👏. Your code was very professional 💯 and I can see you have a great chance to be a Great Software Engineer ⛑️.

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉. And Welcome to Microverse 👋.

> **Note:** You can now take a break even if short before you move on to the next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.


Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@omarramoun](https://img.shields.io/github/followers/omarramoun?label=Ramoun&style=social)](https://github.com/omarramoun)
- This is My **Twitter**: [![@omarramoun](https://img.shields.io/twitter/follow/omarramoun?label=ramoun16&style=social)](https://twitter.com/omarramoun)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 09:31 UTC, ManarOmari commented
Thank you very much for this great support


On Wed, Jun 8, 2022 at 12:13 PM Ramoun ***@***.***> wrote:

> ***@***.**** approved this pull request.
> 🟢 Project Approved! 🏆 Hi @ManarOmari <https://github.com/ManarOmari> 👋
>
> Your project is complete! ✔️ 🏁. This is the First Project 1️⃣ You get
> Approved ✔️! in microverse 🌐.
>
> Finally, *you did it*! 🎉 👏. Your code was very professional 💯 and I
> can see you have a great chance to be a Great Software Engineer ⛑️.
>
> There is nothing else to say other than... *it's time to merge it* [image:
> :shipit:]
> Congratulations! 🎉. And Welcome to Microverse 👋.
>
> *Note:* You can now take a break even if short before you move on to the
> next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.
>
> Cheers and Happy coding!👏👏👏
> Important Notes 📝
>
>    - Feel free to leave any questions or comments in the PR thread if
>    something is not 100% clear.
>    - Please, remember to tag me in your question so I can receive the
>    notification.
>
> Thank you for your time 🙏 and call me if you need help or clarification
> ☎️
>
>    - This is My *GitHub*: [image: @omarramoun]
>    <https://github.com/omarramoun>
>    - This is My *Twitter*: [image: @omarramoun]
>    <https://twitter.com/omarramoun>
>    - This is My *Slack*: [image: Ramoun] <https://slack.com>
>
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ManarOmari/codeReview/pull/1#pullrequestreview-999391152>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIDTEIZBETLUPSU7PJCN7MDVOBP3BANCNFSM5YAC274Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-08 09:32 UTC, merged